### ISSUE TITLE
[auto-generated:e9f7ca9b] Set of overloaded methods must contain original method

### ISSUE THREAD

**Issue by ar-error-reporter** [ml-in-programming/ArchitectureReloaded#158]
- Plugin Name: ArchitectureReloaded
- Plugin Version: 0.1
- OS Name: Windows 10
- Java Version: 1.8.0_144
- Java VM Vendor: Oracle Corporation
- App Name: IDEA
- App Full Name: IntelliJ IDEA
- App Version Name: IntelliJ IDEA
- Is EAP: false
- App Build: IC-171.3780.107
- App Version: 2017.1
- Last Action: Metrics.AutomaticRefactoringAction
- User's Permanent Installation ID: 078ae3d4-10fd-40fb-988b-dc8387d6b07a

```
java.lang.IllegalStateException: Set of overloaded methods must contain original method
	at com.sixrr.metrics.utils.MethodUtils.getOverloads(MethodUtils.java:293)
	at com.sixrr.metrics.utils.MethodUtils.getNumberOfOverloads(MethodUtils.java:300)
	at com.sixrr.stockmetrics.methodCalculators.NumOverloadsCalculator$Visitor.visitMethod(NumOverloadsCalculator.java:20)
	at com.intellij.psi.impl.source.PsiMethodImpl.accept(PsiMethodImpl.java:284)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:200)
	at com.intellij.psi.impl.source.JavaStubPsiElement.acceptChildren(JavaStubPsiElement.java:168)
	at com.intellij.psi.JavaRecursiveElementVisitor.visitElement(JavaRecursiveElementVisitor.java:43)
	at com.intellij.psi.JavaElementVisitor.visitClass(JavaElementVisitor.java:54)
	at com.intellij.psi.impl.source.PsiClassImpl.accept(PsiClassImpl.java:469)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:200)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:853)
	at com.intellij.psi.JavaRecursiveElementVisitor.visitElement(JavaRecursiveElementVisitor.java:43)
	at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:34)
	at com.intellij.psi.JavaElementVisitor.visitJavaFile(JavaElementVisitor.java:335)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.accept(PsiJavaFileBaseImpl.java:464)
	at com.sixrr.stockmetrics.execution.BaseMetricsCalculator$1.run(BaseMetricsCalculator.java:71)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.sixrr.stockmetrics.execution.BaseMetricsCalculator.processFile(BaseMetricsCalculator.java:68)
	at com.sixrr.metrics.metricModel.MetricsExecutionContextImpl$2.visitFile(MetricsExecutionContextImpl.java:129)
	at com.intellij.psi.impl.source.PsiJavaFileBaseImpl.accept(PsiJavaFileBaseImpl.java:467)
	at com.intellij.analysis.AnalysisScope.doProcessFile(AnalysisScope.java:412)
	at com.intellij.analysis.AnalysisScope.lambda$processFile$5(AnalysisScope.java:362)
	at com.intellij.analysis.AnalysisScope.lambda$commitAndRunInSmartMode$6(AnalysisScope.java:379)
	at com.intellij.psi.impl.PsiDocumentManagerBase.lambda$commitAndRunReadAction$1(PsiDocumentManagerBase.java:464)
	at com.intellij.psi.impl.PsiDocumentManagerBase.lambda$commitAndRunReadAction$2(PsiDocumentManagerBase.java:489)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:946)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitAndRunReadAction(PsiDocumentManagerBase.java:487)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitAndRunReadAction(PsiDocumentManagerBase.java:464)
	at com.intellij.analysis.AnalysisScope.commitAndRunInSmartMode(AnalysisScope.java:377)
	at com.intellij.analysis.AnalysisScope.processFile(AnalysisScope.java:364)
	at com.intellij.analysis.AnalysisScope.lambda$accept$0(AnalysisScope.java:284)
	at com.intellij.analysis.AnalysisScope.lambda$createScopeIterator$4(AnalysisScope.java:353)
	at com.intellij.openapi.vfs.VfsUtilCore$1.visitFileEx(VfsUtilCore.java:257)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:272)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:304)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:304)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:304)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:304)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:304)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:304)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:304)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:304)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:304)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:304)
	at com.intellij.openapi.vfs.VfsUtilCore.iterateChildrenRecursively(VfsUtilCore.java:252)
	at com.intellij.openapi.roots.impl.FileIndexBase.iterateContentUnderDirectoryWithFilter(FileIndexBase.java:49)
	at com.intellij.openapi.roots.impl.FileIndexBase.iterateContentUnderDirectory(FileIndexBase.java:43)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.iterateContent(ProjectFileIndexImpl.java:55)
	at com.intellij.analysis.AnalysisScope.accept(AnalysisScope.java:341)
	at com.intellij.analysis.AnalysisScope.accept(AnalysisScope.java:279)
	at com.intellij.analysis.AnalysisScope.accept(AnalysisScope.java:272)
	at com.sixrr.metrics.metricModel.MetricsExecutionContextImpl.calculateMetrics(MetricsExecutionContextImpl.java:105)
	at org.jetbrains.research.groups.ml_methods.algorithm.RefactoringExecutionContext.execute(RefactoringExecutionContext.java:112)
	at org.jetbrains.research.groups.ml_methods.algorithm.RefactoringExecutionContext.access$000(RefactoringExecutionContext.java:38)
	at org.jetbrains.research.groups.ml_methods.algorithm.RefactoringExecutionContext$1.run(RefactoringExecutionContext.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:726)
	at com.intellij.openapi.progress.impl.CoreProgressManager$6.run(CoreProgressManager.java:410)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$9(ApplicationImpl.java:594)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by ujohnny** [comment]
https://github.com/spring-projects/spring-framework.git
