### ISSUE TITLE
[auto-generated:4df39018] com.sixrr.metrics.profile.MetricsProfileRepository cannot be cast to com.sixrr.metrics.profile.MetricsProfileRepository

### ISSUE THREAD

**Issue by ar-error-reporter** [ml-in-programming/ArchitectureReloaded#168]
- Plugin Name: ArchitectureReloaded
- Plugin Version: 0.2
- OS Name: Windows 10
- Java Version: 1.8.0_152-release
- Java VM Vendor: JetBrains s.r.o
- App Name: IDEA
- App Full Name: IntelliJ IDEA
- App Version Name: IntelliJ IDEA
- Is EAP: false
- App Build: IC-173.4674.33
- App Version: 2017.3.5
- Last Action: Metrics.ProjectMetricsAction
- User's Permanent Installation ID: dc4e7dd5-4371-42ef-9c8b-7a0073a45d4f

```
java.lang.ClassCastException: com.sixrr.metrics.profile.MetricsProfileRepository cannot be cast to com.sixrr.metrics.profile.MetricsProfileRepository
	at com.sixrr.metrics.profile.MetricsProfileRepository.getInstance(MetricsProfileRepository.java:56)
	at com.sixrr.metrics.ui.dialogs.ProfileSelectionPanel.<init>(ProfileSelectionPanel.java:39)
	at com.sixrr.metrics.plugin.ProjectMetricsAction.getAdditionalActionSettings(ProjectMetricsAction.java:73)
	at com.intellij.analysis.BaseAnalysisAction$1.getAdditionalActionSettings(BaseAnalysisAction.java:65)
	at com.intellij.analysis.BaseAnalysisActionDialog.createCenterPanel(BaseAnalysisActionDialog.java:229)
	at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1312)
	at com.intellij.analysis.BaseAnalysisActionDialog.<init>(BaseAnalysisActionDialog.java:118)
	at com.intellij.analysis.BaseAnalysisActionDialog.<init>(BaseAnalysisActionDialog.java:86)
	at com.intellij.analysis.BaseAnalysisAction$1.<init>(BaseAnalysisAction.java:57)
	at com.intellij.analysis.BaseAnalysisAction.actionPerformed(BaseAnalysisAction.java:57)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:321)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:911)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:136)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:311)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:130)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:130)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:521)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:48)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:541)
	at java.awt.Component.processMouseEvent(Component.java:6541)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:646)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by ar-error-reporter** [comment]
- Plugin Name: ArchitectureReloaded
- Plugin Version: 0.2
- OS Name: Windows 10
- Java Version: 1.8.0_152-release
- Java VM Vendor: JetBrains s.r.o
- App Name: IDEA
- App Full Name: IntelliJ IDEA
- App Version Name: IntelliJ IDEA
- Is EAP: false
- App Build: IC-173.4674.33
- App Version: 2017.3.5
- Last Action: Metrics.ProjectMetricsAction
- User's Permanent Installation ID: dc4e7dd5-4371-42ef-9c8b-7a0073a45d4f
